# Generated by Django 5.2.5 on 2025-08-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на видео'),
        ),
    ]
